# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-01 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0033_auto_20170121_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamAlly174',
            new_name='ally_174',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamAwards',
            new_name='operation_problems',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamAlliances',
            new_name='team_alliances',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamLikeable',
            new_name='team_auto_abilities',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamOperationProblems',
            new_name='team_likeable',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamOperational',
            new_name='team_operational',
        ),
        migrations.RenameField(
            model_name='teampitscouting',
            old_name='teamOrganized',
            new_name='team_organized',
        ),
        migrations.RemoveField(
            model_name='teampitscouting',
            name='teamSwag',
        ),
    ]
