# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0002_auto_20160310_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmatch',
            name='redAutonA',
            field=models.CharField(default=b'None', max_length=20),
        ),
        migrations.AddField(
            model_name='officialmatch',
            name='redAutonB',
            field=models.CharField(default=b'None', max_length=20),
        ),
        migrations.AddField(
            model_name='officialmatch',
            name='redAutonC',
            field=models.CharField(default=b'None', max_length=20),
        ),
    ]
