# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0003_auto_20160312_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmatch',
            name='blueAutonA',
            field=models.CharField(default=b'None', max_length=20),
        ),
        migrations.AddField(
            model_name='officialmatch',
            name='blueAutonB',
            field=models.CharField(default=b'None', max_length=20),
        ),
        migrations.AddField(
            model_name='officialmatch',
            name='blueAutonC',
            field=models.CharField(default=b'None', max_length=20),
        ),
    ]
