# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0005_auto_20160319_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='homepage',
        ),
    ]
