# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0006_remove_team_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamAlly174',
        ),
    ]
