# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0008_team_teamally174'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Auto',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='ScoreHigh',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='ScoreLow',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='cheval',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='drawbridge',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='drive',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='lowBar',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='moat',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='portcullis',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='ramparts',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='rockwall',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='rough',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='sally',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='scale',
            field=models.CharField(default=b'no', max_length=1000),
        ),
    ]
