# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0010_team_teamalliances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamAlliances',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
