# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0011_auto_20160319_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bookmark',
            field=models.CharField(default=b'no', max_length=1000),
        ),
    ]
