# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0013_auto_20160319_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamAlliances',
            field=models.CharField(default=b' ', max_length=1000),
        ),
    ]
