# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0016_auto_20160320_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bookmark',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamAlliances',
            field=models.CharField(default=b'no', max_length=1000),
        ),
    ]
