# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2016', '0022_officialmatchscoreresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueAutoBouldersHigh',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueAutoBouldersLow',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueAutonA',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueAutonB',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueAutonC',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense1Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense2Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense2Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense3Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense3Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense4Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense4Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense5Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueDefense5Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueFouls',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeam1',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeam2',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeam3',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTechFouls',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeleBouldersHigh',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeleBouldersLow',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTeleDefenseCrossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTowerFaceA',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTowerFaceB',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='blueTowerFaceC',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redAutoBouldersHigh',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redAutoBouldersLow',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redAutonA',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redAutonB',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redAutonC',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense1Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense2Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense2Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense3Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense3Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense4Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense4Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense5Crossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redDefense5Name',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redFouls',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeam1',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeam2',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeam3',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTechFouls',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeleBouldersHigh',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeleBouldersLow',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTeleDefenseCrossings',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTowerFaceA',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTowerFaceB',
        ),
        migrations.RemoveField(
            model_name='officialmatch',
            name='redTowerFaceC',
        ),
    ]
