# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2017', '0002_auto_20170119_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compitition',
            new_name='Competition',
        ),
    ]
