# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2017', '0005_auto_20170208_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='autoFuelHigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='autoFuelLow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='autoMobilityPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='autoPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='autoRotorPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='foulCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='foulPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='kPaRankingPointAchieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='robot1Auto',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='robot2Auto',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='robot3Auto',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor1Auto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor1Engaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor2Auto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor2Engaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor3Engaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotor4Engaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='rotorRankingPointAchieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='techFoulCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopFuelHigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopFuelLow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopFuelPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopRotorPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='teleopTakeoffPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='touchpadFar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='touchpadMiddle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='touchpadNear',
            field=models.IntegerField(default=0),
        ),
    ]
