# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2017', '0006_auto_20170208_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreresult',
            name='defensive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='scored_gear_in_auto',
            field=models.BooleanField(default=False),
        ),
    ]
