# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting2017', '0007_auto_20170211_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialmatchscoreresult',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='officialmatchscoreresult',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='officialmatchscoreresult',
            name='team3',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='defensive',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='scored_gear_in_auto',
        ),
        migrations.AddField(
            model_name='match',
            name='blue1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue1_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='blue2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue2_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='blue3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue3_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='red1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red1_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='red2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red2_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='red3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red3_matches', to='Scouting2017.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialmatchscoreresult',
            name='alliance_color',
            field=models.CharField(choices=[(b'R', b'Red'), (b'B', b'Blue')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='AllanceCompetent',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='AllianceStrategy',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='Competitions',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='CompetnetConfident',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='FuelAcquire',
            field=models.CharField(default='Yes', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='FuelCapacity',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='Gears',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='OrganizedFunctional',
            field=models.CharField(default=b'no', max_length=1000),
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='Random',
            field=models.CharField(default='Random', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='Size',
            field=models.CharField(default='Big', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampitscouting',
            name='Strategy',
            field=models.CharField(default='Strategit', max_length=1000),
            preserve_default=False,
        ),
    ]
